development:
  adapter: postgresql
  encoding: unicode
  database: tanda_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: tanda_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: tanda_production
  pool: 5