# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ab578f07c9b8c080e528ea2c873c1f2e04e82a84233db76597b459514c40b6255cfe545a1bbeb271eaf183951abce83aa92e7ed2e47ebe56358ff8e3ada8cc

test:
  secret_key_base: 1ac8abaaddcbc49ee5c5e5f16946ab8a1fa4edeeeeaee1890103efaf941fbc5b79e218b692c25ffc4ef8588a246f94ad53a0225ec923e1cf8fba1ad830a075f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
